# Copyright 2021 the Tectonic Project
# Licensed under the MIT License.

# See README.md for discussion of features (or lack thereof) in this crate.

[package]
name = "tectonic_engine_xetex"
version = "0.0.0+20210403"
authors = ["Peter Williams <peter@newton.cx>"]
description = """
The [XeTeX](http://xetex.sourceforge.net/) engine as a reusable crate.
"""
homepage = "https://tectonic-typesetting.github.io/"
documentation = "https://docs.rs/tectonic"
repository = "https://github.com/tectonic-typesetting/tectonic/"
readme = "README.md"
license = "MIT"
edition = "2018"
links = "tectonic_engine_xetex"

[dependencies]
libc = "^0.2"
tectonic_bridge_core = { path = "../bridge_core", version ="^0.0.0+20210403"}
tectonic_bridge_flate = { path = "../bridge_flate", version ="^0.1.1"}
tectonic_bridge_graphite2 = { path = "../bridge_graphite2", version ="^0.1.1+20210403"}
tectonic_bridge_harfbuzz = { path = "../bridge_harfbuzz", version ="^0.1.0+20210403"}
tectonic_errors = { path = "../errors", version ="^0.1.0"}
tectonic_io_base = { path = "../io_base", version ="^0.1.0+20210403"}
tectonic_pdf_io = { path = "../pdf_io", version ="^0.0.0+20210403"}
tectonic_status_base = { path = "../status_base", version ="^0.1.0"}
tectonic_xetex_layout = { path = "../xetex_layout", version ="^0.0.0+20210403"}

[build-dependencies]
cbindgen = "^0.16"
cc = "^1.0.66"
tectonic_cfg_support = { path = "../cfg_support", version ="^0.1.2"}

[features]
external-harfbuzz = ["tectonic_bridge_harfbuzz/external-harfbuzz"]

[package.metadata.internal_dep_versions]
tectonic_bridge_core = "925a9a1566aaa4a55d4468d7bf239319828722fb"
tectonic_bridge_flate = "5933308152efb6ba206b4dc01ab6814063b835c0"
tectonic_bridge_graphite2 = "2c1ffcd702a662c003bd3d7d0ca4d169784cb6ad"
tectonic_bridge_harfbuzz = "2c1ffcd702a662c003bd3d7d0ca4d169784cb6ad"
tectonic_cfg_support = "9d5feb40c7ac6958ee3c50604af9271eb2db2b20"
tectonic_errors = "317ae79ceaa2593fb56090e37bf1f5cc24213dd9"
tectonic_io_base = "e33d4ebc956e23d26d2d3331a42cb74ff58d31ae"
tectonic_pdf_io = "620fe47e87000cede22d5e5eafa0fda81f28b402"
tectonic_status_base = "317ae79ceaa2593fb56090e37bf1f5cc24213dd9"
tectonic_xetex_layout = "2c1ffcd702a662c003bd3d7d0ca4d169784cb6ad"
